// React Native Firebase configuration
// This file is automatically generated and used by @react-native-firebase/app

// Note: For React Native Firebase, the configuration is primarily handled by:
// - google-services.json (Android)
// - GoogleService-Info.plist (iOS) 

// For web-based Firebase SDK compatibility, you can also export the config:
export const firebaseConfig = {
  apiKey: "AIzaSyBQT8Ee10axC7rNRXktNra-eaYMhOEi-a8",
  authDomain: "thesis-bbe0c.firebaseapp.com", 
  projectId: "thesis-bbe0c",
  storageBucket: "thesis-bbe0c.firebasestorage.app",
  messagingSenderId: "615143258112",
  appId: "1:615143258112:android:3c91e35397a66bb9d840e5"
};

// Google Sign-In Configuration
// Using only webClientId as recommended by RN Firebase documentation
export const googleSignInConfig = {
  webClientId: '615143258112-gnk282j6e2sauhqh7bvbsngmfsjna5rm.apps.googleusercontent.com',
};

export default firebaseConfig;